### ISSUE TITLE
Close button moves when product view starts dismissing and is cancelled

### ISSUE THREAD

**Issue by warpling** [themonetizr/monetizr-ios-sdk#3]
To reproduce:

1) present a product with `.automatic` modal presentation style
2) start to dismiss the view
3) release to cancel dismissing the view
4) observe the close 'x' moves down 20-30pts

**Comment by armandsavotins** [comment]
Fixed in 97ed9383c3d7b4d02acde40a69a90ab148d57a20

**Comment by warpling** [comment]
I'm still seeing this issue with the latest commit when presenting `.automatic`.
Let me know if I can provide any more info!

**Comment by armandsavotins** [comment]
Can I get the of the info on what kind of device and "orientation" it is happening. It must be due to save area insets just need to figure out where they not updating  as intended.

**Comment by warpling** [comment]
This is in portrait on an iPhone X. Maybe it's because insets are being added when the X is already far below the safeAreaInsets because of the panel style presentation? Seems it should work with two autolayout constraints: one setting top equal to the intended indent and one making it greater than or equal to the topAnchor? Seems like something happening in `viewDidAppear` since it happens after a cancelled dismissal but I could be wrong.

This is in portrait on an iPhone X. Maybe it's because insets are being added when the X is already far below the safeAreaInsets because of the panel style presentation? Seems it should work with two autolayout constraints: one setting top equal to the intended indent and one making it greater than or equal to the topAnchor? Seems like something happening in `viewDidAppear` since it happens after a cancelled dismissal but I could be wrong.

**Comment by armandsavotins** [comment]
Tried different simulators where panel style presentation happens unable to reproduce so far. Some video might be helpful as well. Also could you please ensure latest version is used. There really was a problem but should be fixed in latest release.

**Comment by armandsavotins** [comment]
"X" is relative to top and left Padding of the view. 
Paddings are being updated and constraints reconfigured each time safe area insets are changing to keep "X" of the notch and rounded corners. And it looks like safe area insets do not change when you start dismissing and cancel.

**Comment by armandsavotins** [comment]
https://www.dropbox.com/s/rc961nppez8qun1/Screen%20Recording%202019-10-22%20at%2022.30.mov?dl=0

**Comment by warpling** [comment]
Tested in 3.2.3 and it appears fixed—thanks!

**Comment by warpling** [comment]
Still seems to be printing some debug stuff to the console though ;)

**Comment by armandsavotins** [comment]
Yeah, will remove. Still should printing to console should happen #if DEBUG
